Feat/clients
La-Moderna/papeles-lisos pull request #11
Opened 2021-05-05 00:00 UTC by EdKaram

### Type of Changes

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Deploy to staging (Merge from `dev` to `staging`)
- [ ] Release stable version (Merge from `staging` to `main`)

### Description

Creation of Agent model, creation of ClientsBalance model, unit tests for both models, endpoints creation.

### Motivation and context

Complete functional requirement

### Tests
* Test the functionality
* Add screenshots:

* Run tests with `tox`
* Add screenshot:
* 
![Captura de pantalla (88)](https://user-images.githubusercontent.com/71946314/117083700-e6e55700-ad0a-11eb-8254-62b3abbde051.png)

2021-05-05 02:37 UTC, manuelurgell requested changes

2021-05-05 02:37 UTC, manuelurgell commented on clients/admin.py
> +admin.site.register(Agent, AgentAdmin)
Para seguir la convencion, podrias poner todos los admin.site.register juntos? Al final del archivo

2021-05-05 02:37 UTC, manuelurgell commented on clients/models.py
> +class ClientsBalance(ActiveMixin):
Podrias cambiar el nombre solo a Balance? Con los cambios que implica en la API y en el serializer

2021-05-05 02:37 UTC, manuelurgell commented on clients/serializers.py
> +        fields = ('__all__',)
Con poner `fields = '__all__'` basta

2021-05-05 02:37 UTC, manuelurgell commented on clients/serializers.py
> +        fields = ('__all__',)
Mismo caso, pon `fields = '__all__'`

2021-05-05 02:37 UTC, manuelurgell commented on clients/tests/test_models.py
> +# from unittest import mock
SI no ocupas mock, entonces por favor borra este comentario

2021-05-05 02:37 UTC, manuelurgell commented on clients/models.py
> +    client = models.CharField(max_length=40)
client tambien seria un comentario, porque es la FK hacie ese modelo

2021-05-05 02:37 UTC, manuelurgell commented on clients/models.py
> +    orderBalance = models.CharField(max_length=45)
Este deberia estar en snake case para cumplir con el estandar (order_balance)

2021-05-05 02:37 UTC, manuelurgell commented on clients/tests/test_models.py
> +                user.save()
Para tus pruebas, hace falta agregar las pruebas de los endpoints, `test_api.py`

2021-05-05 02:37 UTC, manuelurgell commented on clients/api.py
> +class ClientBalanceViewSet(mixins.CreateModelMixin,
Veo que de momento solo tienes endpoints de create, no vas a ocupar list, retrieve, update, o delete?

2021-05-05 02:39 UTC, manuelurgell commented
En adicion a lo anterior, en el PR_TEMPLATE npo agregaste las pruebas de funcionalidad, solo las unitarias (las de tox). Las de funcionalidad no son mas que screens de postman donde pruebas los endpoints que create, y del admin donde muestres los modelos que registraste

2021-05-10 03:25 UTC, EdKaram commented
Captura de las pruebas unitarias ya con las de endpoints incluidas
![Captura de pantalla (96)](https://user-images.githubusercontent.com/71946314/117601960-23eb8800-b115-11eb-98d2-4f9efeef2b4b.png)

Capturas de pruebas de funcionalidad
![Captura de pantalla (91)](https://user-images.githubusercontent.com/71946314/117602059-690fba00-b115-11eb-9ff6-4681178c41c4.png)
![Captura de pantalla (92)](https://user-images.githubusercontent.com/71946314/117602060-69a85080-b115-11eb-83ec-b2d6043f9462.png)
![Captura de pantalla (93)](https://user-images.githubusercontent.com/71946314/117602062-69a85080-b115-11eb-88b8-a96e12fabfca.png)
![Captura de pantalla (94)](https://user-images.githubusercontent.com/71946314/117602063-69a85080-b115-11eb-825c-059b8bbb764c.png)

2021-05-10 04:31 UTC, manuelurgell requested changes

2021-05-10 04:31 UTC, manuelurgell commented on clients/tests/test_api.py
> +        self.token = create_token(self.user)
Aquí el token debe sacarse de /auth.

2021-05-10 04:31 UTC, manuelurgell commented on clients/tests/test_api.py
> +class AgentTestEndpoints(APITestCase):
La nomenclatura la puedes consultar en users/tests/test_api.py

2021-05-21 07:02 UTC, manuelurgell requested changes

2021-05-21 07:02 UTC, manuelurgell commented on clients/tests/test_api.py
> +class BalanceTestEndpoints(APITestCase):
Debería llamarase BalanceAPITestCase

2021-05-21 07:02 UTC, manuelurgell commented on clients/tests/test_api.py
> +    """Test /balance model."""
Test /balance endpoints

2021-05-21 07:02 UTC, manuelurgell commented on clients/api.py
> +    list_serializer_class = serializers.BalanceSerializer
El serializer que ocupas para el retrieve debería ser parecido al de list, no uses balance serializer porque entonces de nada sirve el serializer_class

2021-05-21 07:02 UTC, manuelurgell commented on clients/api.py
> +    retrieve_serializer_class = serializers.CreateBalanceSerializer
El retrieve no debería tener un create serializer asociado

2021-05-21 18:02 UTC, manuelurgell requested changes

2021-05-21 18:02 UTC, manuelurgell commented on clients/api.py
> +    retrieve_serializer_class = serializers.CreateAgentSerializer
Por qué utilizas un retrieve_serializer_class con un CreateAgentSerializer? Retrieve y list serializer class van con el retrieveSerializer, create y update serializer class van con el createserializer

2021-05-21 18:02 UTC, manuelurgell commented on clients/api.py
> +    list_serializer_class = serializers.BalanceSerializer
Por favor corrige esto

2021-05-21 18:02 UTC, manuelurgell commented on clients/api.py
> +    retrieve_serializer_class = serializers.CreateBalanceSerializer
Por favor corrige esto

2021-05-21 18:02 UTC, manuelurgell commented on clients/serializers.py
> +class ListAgentSerializer(serializers.ModelSerializer):
Este no debería usarse

2021-05-21 18:02 UTC, manuelurgell commented on clients/serializers.py
> +        fields = ('__all__')
No pongas fields all en el retrive porque entonces desplegarías is_active también, cosa que es un campo interno usado en el borrado lógico

2021-05-21 18:02 UTC, manuelurgell commented on clients/serializers.py
> +class UpdateBalanceSerializer(serializers.ModelSerializer):
Update y create los declaraste iguales,  si es así, entonces sólo usa create

2021-05-22 00:12 UTC, manuelurgell approved these changes

2021-05-22 00:13 UTC, merged