(Fix: Inventories/Warehouses - Api/tests)
La-Moderna/papeles-lisos pull request #13
Opened 2021-05-08 23:21 UTC by MVZHxY

### Type of Changes

- [X] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Deploy to staging (Merge from `dev` to `staging`)
- [ ] Release stable version (Merge from `staging` to `main`)

### Description

Inventory/warehouses model creation, endpoints, test cases with protected endpoints (only admin access - temporary)

### Motivation and context

Fix a previous PR with pertinent changes, protect endpoints and delete unnecessary/not sense functions

### Tests
* Test the functionality
* Add screenshots:

Get warehouses: 
![image](https://user-images.githubusercontent.com/59843857/117190765-6fb0d100-ada5-11eb-957d-7dfb10ad0a0f.png)

Create a  warehouse: 
![image](https://user-images.githubusercontent.com/59843857/117190841-848d6480-ada5-11eb-92fb-74792981e0e9.png)

Fails to create warehouse without require data:
![image](https://user-images.githubusercontent.com/59843857/117191202-e8179200-ada5-11eb-8815-e1521fce8308.png)

Get one warehouse:
![image](https://user-images.githubusercontent.com/59843857/117191282-ffef1600-ada5-11eb-8977-589b6e728e0f.png)

Fails to get not existing warehouse:
![image](https://user-images.githubusercontent.com/59843857/117191329-0d0c0500-ada6-11eb-9b8e-dbed530a48bb.png)

Create inventory:
![image](https://user-images.githubusercontent.com/59843857/117191367-19905d80-ada6-11eb-8b6d-ffc25825e231.png)

Fails to create inventory without required data:
![image](https://user-images.githubusercontent.com/59843857/117191420-2745e300-ada6-11eb-998a-ca4cc7f3cc7f.png)

Get inventories:
![image](https://user-images.githubusercontent.com/59843857/117191459-3462d200-ada6-11eb-8d21-8803939a8d12.png)

Get one inventory:
![image](https://user-images.githubusercontent.com/59843857/117191530-4b092900-ada6-11eb-8653-ebd8a123728a.png)

Fails to get not existing inventory:
![image](https://user-images.githubusercontent.com/59843857/117191600-5b210880-ada6-11eb-8cdf-48cf472a3595.png)

Delete (logically) 1 inventory:
![image](https://user-images.githubusercontent.com/59843857/117191677-74c25000-ada6-11eb-9469-3363a7829594.png)

Delete(logically) 1 warehouse:
![image](https://user-images.githubusercontent.com/59843857/117191759-8c99d400-ada6-11eb-8f5c-eddb258248a7.png)

* Run tests with `tox`
* Add screenshot:

![image](https://user-images.githubusercontent.com/59843857/117556012-160d0880-b02a-11eb-9442-6027fc5059f4.png)

2021-05-10 04:30 UTC, manuelurgell requested changes

2021-05-10 04:30 UTC, manuelurgell commented on inventories/api.py
> +        instance.is_active = False
Si luego de esta línea hacías instance.save ya terminabas. Debido a que probablemente sólo puedas modificar cosas que tienes permiso de ver, deberíamos sobrescribir también el método get_queryset para que filtre sólo con los que tengas en tu catálogo

2021-05-10 04:30 UTC, manuelurgell commented on inventories/tests/test_api.py
> +        self.token = create_token(self.usuario)
Este token debe obtenerse desde /auth

2021-05-10 04:30 UTC, manuelurgell commented on inventories/tests/test_api.py
> +class TestApi(APITestCase):
Sería bueno separar los tests en las rutas que pruebas cada vez, las que tienes en router.register

2021-05-13 19:30 UTC, MVZHxY commented on inventories/tests/test_api.py
> +        self.token = create_token(self.usuario)
Ya quedo, adjunto captura de que tox sigue funcionando
![image](https://user-images.githubusercontent.com/59843857/118176968-b468e780-b3f7-11eb-81e2-ba2004262064.png)

2021-05-13 19:30 UTC, MVZHxY commented on inventories/tests/test_api.py
> +class TestApi(APITestCase):
Creo que ya quedo tambien.

2021-05-13 19:31 UTC, MVZHxY commented on inventories/api.py
> +        instance.is_active = False
Me falta hacer lo del get_queryset, no entiendo muy bien a que te refieres, por lo que supongo te refieres a cambiar el metodo retrieve?

2021-05-20 18:18 UTC, MVZHxY commented
Partial warehouse update: 
![image](https://user-images.githubusercontent.com/59843857/119028659-57c47a00-b96d-11eb-86b2-e7b96c9460c2.png)

Partial inventory update: 
![image](https://user-images.githubusercontent.com/59843857/119028748-6f036780-b96d-11eb-948b-8667ebafbd64.png)

Destroy (logically) inventory:
![image](https://user-images.githubusercontent.com/59843857/119028873-93f7da80-b96d-11eb-8277-42305893b385.png)

(New) Create with custom name/id and django default id (warehouse)
![image](https://user-images.githubusercontent.com/59843857/119029007-ba1d7a80-b96d-11eb-8f00-38fb5c96f861.png)

Destroy(Logically) warehouse:
![image](https://user-images.githubusercontent.com/59843857/119029063-cc97b400-b96d-11eb-8d81-b4b396b2d00e.png)

2021-05-20 22:36 UTC, MVZHxY commented
Ya hice el pull y merge con el dev actual, corregi todos los conflictos que se generaron.

2021-05-21 17:50 UTC, manuelurgell requested changes
En una de las pruebas de fiuncionalidad en postman que pusiste en el PR hay iun list con is_active=False, pero en tu codigo veo que filtras por is_active=True, así que creo que es una imagen vieja. Por favor actualiza las pruebas viejas y, también, sólo déjame las que sean exitosas, no me interesa ver que falle cuando no le mandas el token porque para eso son las unit tests, yo sólo quiero ver que las funcionalidades que declaras (list, create, retrieve, update, destroy) funcionan como deben, así que, a lo mucho, deberían ser 5 screenshots por viewset

2021-05-21 17:50 UTC, manuelurgell commented on app/settings.py
No subas el archivo de setting por favor

2021-05-21 17:50 UTC, manuelurgell commented on inventories/api.py
> +# from django.shortcuts import get_object_or_404
Diría que esta no es una user api, borra este comentario

2021-05-21 17:50 UTC, manuelurgell commented on inventories/api.py
> +            if id is not None and id != old_row.pk:
Quedamos que esto no debería hacerse porque sobrescribir un id implica perder relaciones. Utiliza el id de Django aunado al id de la moderna, y el que si puedes actualizar es el de la moderna (no tiene que ser pk, basta con que sea unique)

2021-05-21 17:50 UTC, manuelurgell commented on inventories/api.py
> +        old_row = get_object_or_404(self.get_queryset(), pk=int(kwargs['pk']))
Mismo comentario sobre la actualización del id

2021-05-21 17:50 UTC, manuelurgell commented on inventories/models.py
> +    class Meta:
class Meta ponlo al final de la clase por favor

2021-05-21 17:50 UTC, manuelurgell commented on inventories/models.py
> +    warehouse_name = models.CharField(max_length=4, unique=True)
Si el modelo es warehouse basta con que se llame name, sería un poco reiterativo llamar a aun objeto warehouse como warehouse.warehouse_name

2021-05-21 17:50 UTC, manuelurgell commented on inventories/models.py
> +    class Meta:
Mismo caso, pon esto al final de la clase

2021-05-21 17:50 UTC, manuelurgell commented on inventories/serializers.py
> +class UpdateWarehouseSerializer(serializers.Serializer):
Si en lugar de un serializer normal usas un model serializer, la validación de la length de description se hace en automático

2021-05-21 17:50 UTC, manuelurgell commented on inventories/serializers.py
> +    def validate_stock(self, stock):
Mismo comentario sobre usar un model serializer

2021-05-21 17:50 UTC, manuelurgell commented on inventories/tests/test_api.py
> +    # Hacer tests de update de parametros
Borra este comentario

2021-05-21 17:50 UTC, manuelurgell commented on inventories/tests/test_models.py
> +class InventoryTestCase(TestCase):
No hay WarehouseTestCase?

2021-05-21 17:50 UTC, manuelurgell commented on inventories/api.py
> +    list_serializer_class = serializers.WarehouseSerializer
List debería utilizar el mismo seriaizer que retrieve

2021-05-21 17:50 UTC, manuelurgell commented on inventories/api.py
> +    create_serializer_class = serializers.CreateWarehouseSerializer
Pon las custom serializer class en el orden: list, create, retrieve, update, destroy

2021-05-22 13:22 UTC, manuelurgell requested changes

2021-05-23 00:29 UTC, MVZHxY commented
Ya corregi el error que me surgio hace rato que hizo fallar al pr

2021-05-23 18:23 UTC, manuelurgell requested changes

2021-05-23 18:23 UTC, manuelurgell commented on inventories/serializers.py
> +class UpdateInventorySerializer(serializers.Serializer):
Me parece que este serializer ya no lo utilizas, podrías revisar qué cosas ya no usas y eliminarlas?

2021-05-23 18:23 UTC, manuelurgell commented on inventories/tests/test_api.py
> +            self.get_inventory_list_url+str(random.randint(1, 10)*5536)
Sólo pon un cliente inexistente, no es encesario que sea uno random

2021-05-23 18:23 UTC, manuelurgell commented on inventories/tests/test_api.py
> +            self.get_warehouse_list_url+str(random.randint(1, 10)*5536))
Igual, no es necesario que sea random

2021-05-23 18:23 UTC, manuelurgell commented on inventories/tests/test_api.py
> +            self.get_warehouse_list_url+"/"+str(random.randint(1, 10)*535))
A veces pones url + id ya  veces url + / + id, cuál es el correcto?

2021-05-23 18:23 UTC, manuelurgell commented on inventories/tests/test_api.py
> +        self.company_1 = Company.objects.create(
Por qué 1 va después de 2?

2021-05-23 18:23 UTC, manuelurgell commented on app/settings.py
> +from re import DEBUG
Tienes que dejar settings en tu local exactamente igual que como se encuentra en dev, y subir el commit a tu branch quitando estos cambios

2021-05-25 17:25 UTC, MVZHxY commented
Ya hice los cambios, copie el settings de dev a mi settings local, asi que son el mismo

2021-05-25 18:19 UTC, manuelurgell requested changes
Por favor agrega pruebas para el on_delete, sea porque es cascade o porque es do_nothing, sea lo que sea

2021-05-25 18:19 UTC, manuelurgell commented on inventories/tests/test_models.py
> +
Como tienes on delete cascade, sería bueno probar que si se borra cuando borras el resto, te paso el código de una prueba para que te bases en ella.

def test_on_delete(self):
        """Test on delete constraints (DO_NOTHING)"""
        project = Project.objects.create(name='Test project on_delete')
        dtype = DatasetType.objects.create(
                name='Test dataset type on_delete',
                project_id=project.id
        )
        dataset = Dataset.objects.create(
                name='Test dataset on_delete',
                type_id=dtype.id
        )
        dtype.delete()
        dataset_qs = Dataset.objects.filter(pk=dataset.pk)
        self.assertEqual(dataset_qs.exists(), True) # Este True, si se cambia por False, revisaría si no existe
        # Once the constraint was tested, delete Dataset
        # to avoid exception on tear_down()
        dataset_qs.delete()

2021-05-27 19:20 UTC, closed without merging