Model company
La-Moderna/papeles-lisos pull request #15
Opened 2021-05-10 02:11 UTC by LuisADR

### Type of Changes

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Deploy to staging (Merge from `dev` to `staging`)
- [ ] Release stable version (Merge from `staging` to `main`)

### Description

- Creation of company models
- Creation of company serializer
- Creation of company endpoints
- Creation of funcion Upload csv
- Creation of UnitTest for company_models, company_endpoints and company_funtions

### Motivation and context

Complete task "Upload company with csv"

### Tests
* Test the functionality
* Add screenshots:

test_models
![image](https://user-images.githubusercontent.com/16786992/117597257-d1a56980-b10a-11eb-8546-2bffb859756d.png)

test_endpoints
![image](https://user-images.githubusercontent.com/16786992/117597299-e681fd00-b10a-11eb-9cf4-ea47e6db3e2d.png)

test_functions
![image](https://user-images.githubusercontent.com/16786992/117597330-f7cb0980-b10a-11eb-8c0b-6c0a54083ad5.png)

* Run tests with `tox`
* Add screenshot:
![image](https://user-images.githubusercontent.com/16786992/117597354-05808f00-b10b-11eb-88ca-16b0bb3c67c2.png)

2021-05-10 03:00 UTC, manuelurgell commented
Tu comando de tox de flake falló, podrías corregir eso?

2021-05-10 12:08 UTC, manuelurgell commented
Ahora no pasó tus pruebas, debería poder completar todas las pruebas unitarias

2021-05-12 17:44 UTC, LuisADR commented
![image](https://user-images.githubusercontent.com/16786992/118020585-d858fa00-b31f-11eb-97d3-2daab0569683.png)

2021-05-12 18:12 UTC, manuelurgell requested changes
En adición a todos los comentarios. En el PR Template noto la ausencia de pruebas de funcionalidad: Deberías mandarme las screens de postman con las pruebas necesarias de tus endpoints, y del Django admin para ver lo nuevo que declaraste

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +        # Save Token
Muchos de estos comentarios los puedes obviar, tampoco es necesario ser sobredescriptivo. Si veo un `self.token = response.data['token']` creo que sabría decir que se está guardando el token, jaja. También, la convención es poner """ """ para comentarios de función y de clase, y # para comentarios de línea, igual y ves más adecuado poner el comentario con """ """ al inicio de la función y nada más

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + self.token)
En el momento que utilizas self.client actualizas el client de todos y no sólo del endpoint, en tal caso, podrías usar un client = self.client  y asignar el token al client en lugar del self.client. Nuevamente, puedes ver la referencia de esto en el test_api de users

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +    def test_get_one_company(self):
Ok, estás probando los endpoints, entonces por favor pon nombres como test_retrieve (el método del viewset que se llama) en lugar de esto

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +        serializer = Company.objects.get(id=self.company_3.id)
Aquí no obtienes "serializer", obtienes "company", cambia el nombre

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +        self.assertEqual(serializer.data, response.data)
Está es una buena forma de revisar tanto los campos como su contenido a la vez, si en algún momento quisieras revisarlo por aparte, puedes el contains (usa de referencia las pruebas de users)

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +    def test_create_companies(self):
Ves? Aquí si es test_create

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +        Company.objects.get(id=company_data['id'])
Esto lo haces pero nunca validas que sea la data respondida, o que no te marque error, o nada. La buena práctica es usar el assert

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
Además del status, revisa que el registro aun exista pero tenga el campo is_active  en False

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +    def test_get_companies_no_authentication(self):
Lo mismo, test list, retrieve, get, create, delete... etc, nada de get_companies o get_one_company

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
También revisa que te regrese el error de missing field (referencia en pruebas de users)

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
Lo mismo, valida el error

2021-05-12 18:12 UTC, manuelurgell commented on companies/tests/test_api.py
> +            self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
Lo mismo, valida el error. En adición, estas tres funciones podrían ser una sola prieba de "missing fields" y ya pruebas todas las combinaciones

2021-05-13 16:13 UTC, LuisADR commented on companies/api.py
> +    queryset = models.Company.objects.all()
Sobre los permisos no lo tengo del todo claro, pero lo conveniente es que dependiendo del permiso de cada usuario pueda ver toda las listas o solo con las que esta relacionado

2021-05-13 16:14 UTC, LuisADR commented on companies/api.py
> +        if company_serializer.is_valid():
Deje el create del mixins, aunque en ese caso seria innecesario sobrescribir create_serializer_class?

2021-05-13 16:42 UTC, LuisADR commented on companies/serializers.py
> +class UpdateCompanySerializer(serializers.Serializer):
Se debería, ya actualice el método y agregue una prueba unitaria

2021-05-13 17:02 UTC, LuisADR commented
![image](https://user-images.githubusercontent.com/16786992/118159817-1f5bf380-b3e3-11eb-82ce-e387320dcbe0.png)

2021-05-13 17:05 UTC, manuelurgell commented on companies/api.py
> +    queryset = models.Company.objects.all()
Bueno, respecto a los permisos se puede cambiar luego, pero si debes dejar sólo los que tengan is_active en True o podrías ver objetos borrados (borrado lógico)

2021-05-13 17:05 UTC, manuelurgell commented
> En adición a todos los comentarios. En el PR Template noto la ausencia de pruebas de funcionalidad: Deberías mandarme las screens de postman con las pruebas necesarias de tus endpoints, y del Django admin para ver lo nuevo que declaraste

Aun no pones eso en tu PR

2021-05-13 17:09 UTC, manuelurgell requested changes

2021-05-13 17:09 UTC, manuelurgell commented on companies/admin.py
> +    pass
pass? No vas a enseñas ningún campo usando algo como list_display?

2021-05-13 17:09 UTC, manuelurgell commented on companies/api.py
> +    def partial_update(self, request, pk=None):
Por favor revisemos entonces cómo hacer esto mejor en una llamada

2021-05-13 17:09 UTC, manuelurgell commented on companies/serializers.py
> +class UpdateCompanySerializer(serializers.Serializer):
No, no se debería pues eso es parte del borrado lógico

2021-05-13 17:09 UTC, manuelurgell commented on companies/serializers.py
> +    def update(self, instance, validated_data):
En qué momento haces uso de este método?

2021-05-13 17:09 UTC, manuelurgell commented on companies/tests/test_api.py
> +        self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + self.token)
No realizaste este cambio

2021-05-13 17:56 UTC, LuisADR commented on companies/serializers.py
> +class UpdateCompanySerializer(serializers.Serializer):
Envía un error al querer actualizar el campo

2021-05-13 18:05 UTC, manuelurgell commented on companies/serializers.py
> +class UpdateCompanySerializer(serializers.Serializer):
No, ni siquiera debería tratar de actualizarlo. el serializer.validated_data ya te quita los campos sobrantes

2021-05-16 19:48 UTC, manuelurgell approved these changes

2021-05-16 19:49 UTC, merged