Fixes/merge inventories
La-Moderna/papeles-lisos pull request #19
Opened 2021-05-27 19:04 UTC by MVZHxY

### Type of Changes

- [X] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Deploy to staging (Merge from `dev` to `staging`)
- [ ] Release stable version (Merge from `staging` to `main`)

### Description

Inventory/warehouses model creation, endpoints, test cases with protected endpoints (only admin access - temporary)

### Motivation and context

Fix a previous PR with pertinent changes, protect endpoints and delete unnecessary/not sense functions

### Tests
* Test the functionality
* Add screenshots:

List warehouses: 
![image](https://user-images.githubusercontent.com/59843857/117190765-6fb0d100-ada5-11eb-957d-7dfb10ad0a0f.png)

Create a  warehouse: 
![image](https://user-images.githubusercontent.com/59843857/117190841-848d6480-ada5-11eb-92fb-74792981e0e9.png)

Retrieve warehouse:
![image](https://user-images.githubusercontent.com/59843857/117191282-ffef1600-ada5-11eb-8977-589b6e728e0f.png)

Create inventory:
![image](https://user-images.githubusercontent.com/59843857/117191367-19905d80-ada6-11eb-8b6d-ffc25825e231.png)

List inventories:
![image](https://user-images.githubusercontent.com/59843857/117191459-3462d200-ada6-11eb-8d21-8803939a8d12.png)

Retrieve inventory:
![image](https://user-images.githubusercontent.com/59843857/117191530-4b092900-ada6-11eb-8653-ebd8a123728a.png)

Delete (logically) 1 inventory:
![image](https://user-images.githubusercontent.com/59843857/117191677-74c25000-ada6-11eb-9469-3363a7829594.png)

Delete(logically) 1 warehouse:
![image](https://user-images.githubusercontent.com/59843857/117191759-8c99d400-ada6-11eb-8f5c-eddb258248a7.png)

Partial warehouse update: 
![image](https://user-images.githubusercontent.com/59843857/119028659-57c47a00-b96d-11eb-86b2-e7b96c9460c2.png)

Partial inventory update: 
![image](https://user-images.githubusercontent.com/59843857/119028748-6f036780-b96d-11eb-948b-8667ebafbd64.png)

Destroy (logically) inventory:
![image](https://user-images.githubusercontent.com/59843857/119028873-93f7da80-b96d-11eb-8277-42305893b385.png)

(New) Create with custom name/id and django default id (warehouse)
![image](https://user-images.githubusercontent.com/59843857/119029007-ba1d7a80-b96d-11eb-8f00-38fb5c96f861.png)

Destroy(Logically) warehouse:
![image](https://user-images.githubusercontent.com/59843857/119029063-cc97b400-b96d-11eb-8d81-b4b396b2d00e.png)

2021-05-27 19:05 UTC, MVZHxY commented
Ya agregue los cambios solicitados en el PR de inventories/Warehouses_fixes, lo subo en una branch diferente debido a que me pedia hacer pull de dicha branch cuando ya tenia todo actualizado, por lo que para evitar posibles problemas lo hice en una nueva. Estan tambien los cambios correspondientes de dev para un merge mas fluido.

2021-05-29 17:36 UTC, manuelurgell requested changes

2021-05-29 17:36 UTC, manuelurgell commented on inventories/tests/test_models.py
> +        """Test on delete constraints (DO_NOTHING)"""
La prueba dice que estás probando el DO_NOTHING, pero al final lo revisas y no existe: "inventory_qs.exists(), False"

2021-05-31 18:58 UTC, manuelurgell approved these changes

2021-05-31 18:58 UTC, merged