Feat/order
La-Moderna/papeles-lisos pull request #23
Opened 2021-06-09 14:47 UTC by LuisADR

### Type of Changes

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Deploy to staging (Merge from `dev` to `staging`)
- [ ] Release stable version (Merge from `staging` to `main`)

### Description

Create Order Tables

### Motivation and context

Lorem Impsum Dolor.

2021-06-09 23:48 UTC, manuelurgell requested changes

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +    queryset = Order.objects.all()
queryset va despues de las serializer classes

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +    list_serializer_class = serializers.OrderSerializer
el orden es list, create, retrieve, update, destroy

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +        order_serializer = serializers.CreateOrderSerializer(
Si ibas a hacer esto, basta con self.get_serializer(data=request.data, action='create')

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +        if order_serializer.is_valid():
Te ahorras el if else solo poniendo order_serializer.is_valid(raise_exception=True)

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +            order = Order.objects.create()
Crealo utilizando un model serializer o al menos poniendo todos los campos dentro del create. Es menos eficiente crear el objeto y luego actualizar los campos uno a uno

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +        if (not order_detail_serializer.is_valid()):
Te ahorras el if solo poniendo order_detail_serializer.is_valid(raise_exception=True)

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +            authorization = Authorization.objects.create(
Si en algun punto falla te quedarias con modelos a medio crear, pon en la exception que si entra, trate de borrar todo lo que creaste

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +            )
Esta mal indentado

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +    retrieve_serializer_class = serializers.AuthorizationSerializer
Si para el retrieve ocupas el mismo serializer que la serializer class, no vale la pena que ocupes nuestros custom mixins, usa el de rest_framework "mixins.RetrieveModelMixin" y quitas la retrieve_serializer_class

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
>      def list(self, request, *args, **kwargs):
De que sirve que sobrescribas el list si  vas a terminar haciendo lo mismo que heradas? Ademas, no heredas un List Model Mixin

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +    r'order',
orders

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +    'order'
basename='order'

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +    r'order/detail',
orders/details

2021-06-09 23:48 UTC, manuelurgell commented on orders/api.py
> +    'order-detail'
basename='order-details'

2021-06-09 23:48 UTC, manuelurgell commented on orders/migrations/0001_initial.py
> +# Generated by Django 3.2 on 2021-06-09 08:55
Estas sobrescribiendo una migracion de hace 3 dias, eso generara conflictos con loos demas. En lugar de hacer esto, deja la migracion como estaba y solo agrega la nueva (o acaso genera conflictos como la ultima vez que tuvimos que sobrescribir migraciones?)

2021-06-09 23:48 UTC, manuelurgell commented on orders/models.py
> +class Order(ActiveMixin):
Ponle verbose name y define str para los modelos que creaste y para los pasados (consulta el modelo de Users o de Clients para mas info)

2021-06-10 02:07 UTC, LuisADR commented on orders/api.py
> +            order = Order.objects.create()
Lo creo porque por el moemnto ocupo el id de django como ordenVenta, su se cambaira esa parte, lo cambio a un serializer

2021-06-10 02:43 UTC, manuelurgell commented on orders/api.py
> +            order = Order.objects.create()
Pero me refiero a que en lugar de hacer create y luego meterle cada campo uno a uno, pues mete todos del madrazo al create no?

2021-06-10 02:47 UTC, manuelurgell approved these changes

2021-06-10 02:51 UTC, merged